koorsuch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from koorsuch_app import urls

urlpatterns = [
    url(r'^koorsuch/', include('koorsuch_app.urls')),
    url(r'^admin/', admin.site.urls),
]

koorsuch_app/urls.py
from django.conf.urls import url

from . import views
from koorsuch_app.views import CableFormView

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^extra/$', CableFormView.as_view()),
]

koorsuch_app/models.py
from django.db import models
from django.forms import ModelForm
from django.core.validators import MaxValueValidator, MinValueValidator

from .choices import *
# default="E" means that current value should've been selected from the list but not missed
class Spec(models.Model):

    material = models.CharField(max_length=2, choices=MATERIAL_CHOICES, blank=True)
    insulation = models.CharField(max_length=100, choices=INSULATION_CHOICES, default='E')
    armor = models.CharField(max_length=100, choices=ARMOR_CHOICES, default='E')
    protection = models.CharField(max_length=150, choices=PROTECTION_CHOICES, default="E")
    screening = models.CharField(max_length=100, choices=SCREEN_CHOICES, blank=True)
    firefighting_cat = models.CharField(max_length=300, choices=FIREFIGHTING_CAT_CHOICES, blank=True)

    # TODO: make following unavailable when ff_cat is blank

    firefighting_spec = models.CharField(max_length=200, choices=FIREFIGHTING_SPEC_CHOICES, null=True, blank=True)
    shape = models.CharField(max_length=50, choices=SHAPE_CHOICES, default="E", blank=True)
    implementation = models.CharField(max_length=100, choices=IMPLEMENTATION_CHOICES, default="E")
    climate = models.CharField(max_length=100, choices=CLIMATE_CHOICES, null=True)

    def __str__(self):
        return self.material + self.insulation + self.protection + self.armor + self.screening


class Cable(models.Model):
    name = models.CharField(max_length=100)
    spec = models.ForeignKey(Spec)
    wire = models.IntegerField(default=2, validators=[
        MaxValueValidator(5),
        MinValueValidator(1)
    ])
    extra_wires = models.IntegerField(blank=True, null=True, default=0, validators=[
        MaxValueValidator(3),
        MinValueValidator(0)
    ])
    gauge = models.FloatField(choices=GAUGE_CHOICES, default=0)

    extra_gauge = models.FloatField(choices=GAUGE_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.name

koorsuch_app/views.py
from django.shortcuts import render
from django.views import View

from .models import Spec, Cable
from .form import CableForm


class CableFormView(View):
    form_class = CableForm
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        # dunno wat is this
        form = self.form_class()
        return render(request, 'koorsuch/index.html', {'form': form})


def index(request):
    cables = Cable.objects.all()
    # говнокод во все поля
    if 'nm' in request.GET:
        cables = cables.filter(name__contains=request.GET['nm'])
    if 'mt' in request.GET and request.GET['mt'] != '~':
        cables = cables.filter(spec__material=request.GET['mt'])
    if 'is' in request.GET and request.GET['is'] != '':
        cables = cables.filter(spec__insulation=request.GET['is'])
    if 'ar' in request.GET and request.GET['ar'] != '':
        cables = cables.filter(spec__armor=request.GET['ar'])
    if 'pr' in request.GET and request.GET['pr'] != '':
        cables = cables.filter(spec__protection=request.GET['pr'])
    if 'sc' in request.GET and request.GET['sc'] != '~':
        cables = cables.filter(spec__screening=request.GET['sc'])
    if 'ff' in request.GET and request.GET['ff'] != '~':
        cables = cables.filter(spec__firefighting_cat=request.GET['ff'])
    if 'im' in request.GET and request.GET['im'] != '':
        cables = cables.filter(spec__implementation=request.GET['im'])
    if 'sh' in request.GET and request.GET['sh'] != '':
        cables = cables.filter(spec__shape=request.GET['sh'])
    if 'cl' in request.GET and request.GET['cl'] != '':
        cables = cables.filter(spec__climate=request.GET['cl'])
    if 'wr' in request.GET and request.GET['wr'] != '':
        cables = cables.filter(wire=request.GET['wr'])
    if 'xwr' in request.GET and request.GET['xwr'] != '':
        cables = cables.filter(extra_wires=request.GET['xwr'])
    if 'ga' in request.GET and request.GET['ga'] != '':
        cables = cables.filter(gauge__lte=request.GET['ga'])
    if 'xga' in request.GET and request.GET['xga'] != '':
        cables = cables.filter(extra_gauge__lte=request.GET['xga'])

    context = {
        'cables': cables,
    }

    return render(request, 'koorsuch/index.html', context)

koorsuch_app/templates/koorsuch/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns:background-color="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Wires koorsuch</title>

    <!-- Bootstrap -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Some wires over here</h1>

    <h3>Search:</h3>

    <form id="searchform"  method="get" accept-charset="utf-8">
      <table class=".table-hover">
        <tr>
          <input class="searchfield" id="searchbox" name="nm" type="text" placeholder="Name...">
        </tr>
<br>
        <tr>
          <select name="mt">
            <option value="~">Материал:</option>
            <option value="">Медь</option>
            <option value="А">Алюминий</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="is">
            <option value="">Изоляция:</option>
            <option value="В">ПВХ</option>
            <option value="Пв">ПЭТ</option>
            <option value="П">Полимеры</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="ar">
            <option value="">Броня:</option>
            <option value="Г">Небронированный</option>
            <option value="Б">Стальные ленты</option>
            <option value="Ба">Ленты алюминия</option>
            <option value="К">Проволоки алюминия</option>
            <option value="Ка">Стальные проволоки</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="pr">
            <option value="">Защита:</option>
            <option value="В">Оболочка ПВХ</option>
            <option value="Б">Стальные ленты</option>
            <option value="Ба">Ленты алюминия</option>
            <option value="К">Проволоки алюминия</option>
            <option value="Ка">Стальные проволоки</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="sc">
            <option value="~">Экранирование:</option>
            <option value="">Без экрана</option>
            <option value="Э">С экраном</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="ff">
            <option value="~">Пожарозащита:</option>
            <option value="">При одиночной прокладке</option>
            <option value="нг(A F/R)">По категории A F\R</option>
            <option value="нг(A)">По категории A</option>
            <option value="нг(B)">По категории B</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="im">
            <option value="">Исполнение:</option>
            <option value="ок">Однопроволочные круглые</option>
            <option value="мк">Многопроволочные круглые</option>
            <option value="ос">Однопроволочные сегментные</option>
            <option value="мс">Многопроволочные сегментные</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="wr">
            <option value="">Число проводников:</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </tr>
<br>
        <tr>
          <select name="xwr">
            <option value="">Число доп проводников:</option>
            <option value="0">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
          </select>
        </tr>
        <br>
        <tr>
          <input class="searchfield" id="gauge" name="ga" type="text" placeholder="Толщина жил">
        </tr>
<br>
        <tr>
          <input class="searchfield" id="xgauge" name="xga" type="text" placeholder="Толщина доп жил">
        </tr>
      </table>


      <button class="searchbutton" type="submit">Filter
      </button>
      <!--magic-->
      <button class="searchbutton" >Drop
      </button>
    </form>

    <h3>Result:</h3>
    {% if cables %}

    <table class="table">
      <thead>
        <tr>
          <td>Название</td>
          <td>Материал</td>
          <td>Изоляция</td>
          <td>Броня</td>
          <td>Защита</td>
          <td>Экранирование</td>
          <td>Класс пожароопасности</td>
          <td>Исполнение жил</td>
          <td>Поперечное сечение жил</td>
          <td>Климатическое исполнение</td>
          <td>Число жил кабеля</td>
          <td>Толщина жилы</td>
          <td>Число дополнительных жил кабеля</td>
          <td>Толщина дополнительных жил</td>
        </tr>
      </thead>
    {% for c in cables %}
        <tr>
          <td>{{ c.name }}</td>
          <td>{{ c.spec.get_material_display }}</td>
          <td>{{ c.spec.get_insulation_display }}</td>
          <td>{{ c.spec.get_armor_display }}</td>
          <td>{{ c.spec.get_protection_display }}</td>
          <td>{{ c.spec.get_screening_display }}</td>
          <td>
            {{ c.spec.get_firefighting_cat_display }}
            {% if c.spec.firefighting_spec %}
              {{ c.spec.get_firefighting_spec_display }}
            {% endif %}
          </td>
          <td>{{ c.spec.get_implementation_display }}</td>
          <td>{{ c.spec.get_shape_display }}</td>
          <td>{{ c.spec.get_climate_display }}</td>
          <td>{{ c.wire }}</td>
          <td>{{ c.gauge }}</td>
          <td>{{ c.extra_wires }}</td>
          <td>{{ c.extra_gauge}}</td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No cables are available.</p>
{% endif %}

    <p>some add wires features</p>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
  </body>
</html>